version: 1
groups:
  - annotation: ckanext-citeproc settings
    options:
      - key: ckanext.citeproc.citation_styles_path
        default: None
        description: |
          Specifies the absolute path on the server to the directory containing the CSL files.
          The available citation formats will be built from any CSL files in this directory.
          See: https://github.com/citation-style-language/styles
        example: /path/to/csl/styles/directory/
        required: true
      - key: ckanext.citeproc.dataset_citations
        default: true
        type: bool
        description: |
          Whether ot not to show citations for datasets of a certain dataset type.
          Such as ckanext.citeproc.<package type>_show_citations
        example: false
        validators: ignore_missing
        required: false
      - key: ckanext.citeproc.dataset_resource_citations
        default: true
        type: bool
        description: |
          Whether ot not to show citations for resources of a certain dataset type.
          Such as ckanext.citeproc.<package type>_resource_show_citations
        example: false
        validators: ignore_missing
        required: false
